// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	RequestMessage
	ResponseMessage
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type RequestMessage_RequestType int32

const (
	RequestMessage_PLAIN RequestMessage_RequestType = 0
	RequestMessage_WINCH RequestMessage_RequestType = 1
)

var RequestMessage_RequestType_name = map[int32]string{
	0: "PLAIN",
	1: "WINCH",
}
var RequestMessage_RequestType_value = map[string]int32{
	"PLAIN": 0,
	"WINCH": 1,
}

func (x RequestMessage_RequestType) String() string {
	return proto.EnumName(RequestMessage_RequestType_name, int32(x))
}
func (RequestMessage_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type ResponseMessage_ResponseType int32

const (
	ResponseMessage_STDOUT ResponseMessage_ResponseType = 0
	ResponseMessage_STDERR ResponseMessage_ResponseType = 1
	ResponseMessage_CLOSE  ResponseMessage_ResponseType = 2
)

var ResponseMessage_ResponseType_name = map[int32]string{
	0: "STDOUT",
	1: "STDERR",
	2: "CLOSE",
}
var ResponseMessage_ResponseType_value = map[string]int32{
	"STDOUT": 0,
	"STDERR": 1,
	"CLOSE":  2,
}

func (x ResponseMessage_ResponseType) String() string {
	return proto.EnumName(ResponseMessage_ResponseType_name, int32(x))
}
func (ResponseMessage_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type RequestMessage struct {
	MsgType RequestMessage_RequestType `protobuf:"varint,1,opt,name=msgType,enum=message.RequestMessage_RequestType" json:"msgType,omitempty"`
	Content []byte                     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *RequestMessage) Reset()                    { *m = RequestMessage{} }
func (m *RequestMessage) String() string            { return proto.CompactTextString(m) }
func (*RequestMessage) ProtoMessage()               {}
func (*RequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResponseMessage struct {
	MsgType ResponseMessage_ResponseType `protobuf:"varint,1,opt,name=msgType,enum=message.ResponseMessage_ResponseType" json:"msgType,omitempty"`
	Content []byte                       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *ResponseMessage) Reset()                    { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string            { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()               {}
func (*ResponseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*RequestMessage)(nil), "message.RequestMessage")
	proto.RegisterType((*ResponseMessage)(nil), "message.ResponseMessage")
	proto.RegisterEnum("message.RequestMessage_RequestType", RequestMessage_RequestType_name, RequestMessage_RequestType_value)
	proto.RegisterEnum("message.ResponseMessage_ResponseType", ResponseMessage_ResponseType_name, ResponseMessage_ResponseType_value)
}

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xfa, 0x18,
	0xb9, 0xf8, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x7c, 0x21, 0x42, 0x42, 0xb6, 0x5c, 0xec,
	0xb9, 0xc5, 0xe9, 0x21, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0xca, 0x7a,
	0x30, 0xcd, 0xa8, 0x2a, 0x61, 0x5c, 0x90, 0xd2, 0x20, 0x98, 0x1e, 0x21, 0x09, 0x2e, 0xf6, 0xe4,
	0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x26, 0xa0, 0x76, 0x9e, 0x20, 0x18, 0x57, 0x49, 0x99,
	0x8b, 0x1b, 0x49, 0x87, 0x10, 0x27, 0x17, 0x6b, 0x80, 0x8f, 0xa3, 0xa7, 0x9f, 0x00, 0x03, 0x88,
	0x19, 0xee, 0xe9, 0xe7, 0xec, 0x21, 0xc0, 0xa8, 0x34, 0x9f, 0x91, 0x8b, 0x3f, 0x28, 0xb5, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x15, 0xe6, 0x22, 0x7b, 0x74, 0x17, 0xa9, 0x22, 0xb9, 0x08, 0x45, 0x29,
	0x9c, 0x4f, 0xac, 0x9b, 0x0c, 0xb9, 0x78, 0x90, 0xb5, 0x08, 0x71, 0x71, 0xb1, 0x05, 0x87, 0xb8,
	0xf8, 0x87, 0x86, 0x00, 0x5d, 0x05, 0x61, 0xbb, 0x06, 0x05, 0x09, 0x30, 0x82, 0x5c, 0xe8, 0xec,
	0xe3, 0x1f, 0xec, 0x2a, 0xc0, 0x94, 0xc4, 0x06, 0x0e, 0x42, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x81, 0x21, 0x39, 0xc2, 0x53, 0x01, 0x00, 0x00,
}
